apiVersion: apps/v1
kind: Deployment
metadata:
  name:  customer-comment-analyzer
spec: 
  selector:
    matchLabels:
      app: customer-comment-analyzer
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: customer-comment-analyzer
    spec: 
      containers:
        - name: customer-comment-analyzer
          image: pierre112/customer-comment-analyzer:latest
          imagePullPolicy: Never
          ports: 
            - containerPort: 3000
          
